### ISSUE TITLE
Missing Lecture 2 Video

### ISSUE THREAD

**Issue by serghost** [Sorosliu1029/6.S081#2]
Hello,

I noticed that there is no video available for Lecture 2 in the course repository. Do you happen to know if there are any alternative resources available for this lecture?

Any information you can provide would be greatly appreciated.
Thank you for your time and assistance in this matter

**Comment by Sorosliu1029** [comment]
sorry, I have no idea. You can refer to [the schedule on official website](https://pdos.csail.mit.edu/6.S081/2021/schedule.html) for more information.

I think the provided pdfs is enough for the topic of lecture 2.
